cookbook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='home'),
    path('catalogue', views.catalogue, name='catalogue'),
    path('favourites', views.favourites, name='favourites'),
    path('search', views.search, name='search'),
    path('new', views.new, name='new'),
    path('profile', views.profile, name='profile'),
    path('signup', views.signup, name='signup'),
    path('users', views.users, name='users'),
    path('about', views.about, name='about'),
]

main/models.py
from django.db import models


class Ingredient(models.Model):
    # Recipe-Ingredient M-M in Recipe

    name = models.CharField('Ingredient Name', max_length=50, default="Default Ingredient", null=True)

    def __str__(self):
        return self.title


class Recipe(models.Model):
    # Recipe-Ingredient M-M
    ingredient = models.ForeignKey(Ingredient, on_delete=models.PROTECT, default="Default Ingredient", null=True)

    title = models.CharField('Recipe Name', max_length=50, default="Default Title", null=True)
    description = models.TextField('Description', default="Default Description", null=True)
    favourite = models.BooleanField('Favourite', default=False, null=True)

    def __str__(self):
        return self.title  # Shows text in Query output

main/forms.py
from .models import Recipe, Ingredient
from django.forms import ModelForm, TextInput, Textarea, PasswordInput, CheckboxInput


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ["title", "description", "favourite"]
        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Recipe name'
            }),
            "description": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Recipe description'
            }),
            "favourite": CheckboxInput(attrs={
                # 'placeholder': 'Favourite',
                # 'class': 'form-control'
            }),
        }


class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = ["name"]
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingredient name'
            }),
        }

main/views.py
from django.shortcuts import render, redirect

from .forms import RecipeForm
from .models import Recipe


def index(request):
    context = {
        'title': 'Home',
    }
    return render(request, 'main/index.html', context)


def catalogue(request):
    recipes = Recipe.objects.order_by('id')[:10]
    context = {
        'title': 'Catalogue',
        'recipes': recipes
    }
    return render(request, 'main/catalogue.html', context)


def favourites(request):
    recipes = Recipe.objects.order_by('id')[:10]
    context = {
        'title': 'Favourites',
        'recipes': recipes
    }
    return render(request, 'main/favourites.html', context)


def search(request):
    context = {
        'title': 'Search',
    }
    return render(request, 'main/search.html', context)


def new(request):
    error = ''
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:catalogue')
        else:
            error = 'Wrong input.'

    form = RecipeForm
    context = {
        'title': 'Edit recipe',
        'form': form,
        'error': error
    }
    return render(request, 'main/new.html', context)


def profile(request):
    context = {
        'title': 'Profile',
    }
    return render(request, 'main/profile.html', context)


def signup(request):
    context = {
        'title': 'Sign Up',
    }
    return render(request, 'main/signup.html', context)


def users(request):
    context = {
        'title': 'Users',
    }
    return render(request, 'main/users.html', context)

def about(request):
    context = {
        'title': 'About',
    }
    return render(request, 'main/about.html', context)

main/templates/main/about.html
{% extends 'main/base1.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Some info</p>
{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-body border-bottom shadow-sm">
        <p class="h5 my-0 mr-md-auto fw-normal">Cook Book</p>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'main:home' %}">Main Page</a>
            <a class="p-2 text-dark" href="{% url 'main:catalogue' %}">Catalogue</a>
            <a class="p-2 text-dark" href="{% url 'main:about' %}">About</a>
        </nav>
        <a class="btn btn-outline-primary" href="#">Sign up</a>
    </header>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

main/templates/main/base1.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-body border-bottom shadow-sm">
        <p class="h5 my-0 mr-md-auto fw-normal">Cook Book</p>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'main:home' %}">Main Page</a>
            <a class="p-2 text-dark" href="{% url 'main:catalogue' %}">Catalogue</a>
            <a class="p-2 text-dark" href="{% url 'main:search' %}">Search</a>
            <a class="p-2 text-dark" href="{% url 'main:profile' %}">Profile</a>
            <a class="p-2 text-dark" href="{% url 'main:about' %}">About</a>
        </nav>
        <a class="btn btn-outline-primary" href="{% url 'main:signup' %}">Sign up</a>
    </header>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

main/templates/main/base2.html
<!-- https://getbootstrap.com/docs/5.0/examples/ -->
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
              <ul class="dropdown-menu" aria-labelledby="dropdown01">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
</body>
</html>

main/templates/main/catalogue.html
{% extends 'main/base1.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Catalogue</h1>
    {% if recipes %}
        {% for x in recipes %}
            <div class="alert mt-2"> <!  alert-warning == Yellow box around div block >
                <h3>{{ x.title }}</h3>
                <h5>Favourite: {{ x.favourite }}</h5>
                <p>{{ x.description }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>Still no recipes!</p>
    {% endif %}
{% endblock %}

main/templates/main/favourites.html
{% extends 'main/base1.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Favourite Recipes</h1>
        {% for x in recipes %}
            {% if x.favourite %}
            <div class="alert mt-2"> <!  alert-warning == Yellow box around div block >
                <h3>{{ x.title }}</h3>
                <h5>Favourite: {{ x.favourite }}</h5>
                <p>{{ x.description }}</p>
            </div>
            {% endif %}
        {% endfor %}
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Main Page</h1>
    <p>Some text</p>
{% endblock %}

main/templates/main/new.html
{% extends 'main/base1.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Edit recipe</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.description }}<br>
        <h4>Favourite: {{ form.favourite }}</h4><br>
        <button type="submit" class="btn btn-success">Save</button>
        <span>{{ error }}</span>
    </form>
{% endblock %}

main/templates/main/profile.html
{% extends 'main/base1.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-body border-bottom shadow-sm">
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'main:new' %}">New</a>
            <a class="p-2 text-dark" href="{% url 'main:favourites' %}">Favourites</a>
            <a class="p-2 text-dark" href="{% url 'main:users' %}">Users</a>
        </nav>
    </header>
    <h1>Profile</h1>
    <div class="alert mt-2"> <!  alert-warning == Yellow box around div block >
        <h4>First Name: {{ user.firstname }}</h4>
        <h4>Last Name: {{ user.lastname }}</h4>
        <h4>Login: {{ user.login }}</h4>
    </div>
{% endblock %}

main/templates/main/search.html
{% extends 'main/base1.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Search</h1>
{% endblock %}

main/templates/main/signup.html
{% extends 'main/base1.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Sign up</h1>

{% endblock %}

main/templates/main/users.html
{% extends 'main/base1.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Users</h1>

{% endblock %}